### ISSUE TITLE
Chapter 9. 디플로이먼트: 선언적 애플리케이션 업데이트

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kubernetes-study#10]

**Comment by kmg28801** [comment]
# 파드에서 실행 중인 애플리케이션 업데이트


- 쿠버네티스에서 실행되는 애플리케이션의 기본 구성
![image](https://user-images.githubusercontent.com/53685313/211147597-c0131814-f7b5-4011-8c6d-e8ffd82dffec.png)

- 모든 파드를 업데이트하는 방법
  - 기존 파드를 모두 삭제한 다음 새 파드를 시작
    - 단점 : 짧은 시간 동안 애플리케이션을 사용할 수 없다.
  - 새로운 파드를 시작하고, 기동하면 기존 파드를 삭제. 새 파드를 모두 추가한 다음 한꺼번에 기존 파드를 삭제하거나 순차적으로 새 파드를 추가하고 기존 파드를 점진적으로 제거해 이 작업을 수행
     - 단점 : 애플리케이션이 배포 시점에는 동시에 두 가지 버전이 존재함


### 오래된 파드를 삭제하고 새 파드로 교체

- 레플리케이션컨트롤러의 파드 템플릿은 언제든지 업데이트가 가능하다.
- 레플리케이션컨트롤러는 새 인스턴스를 생성할 때 업데이트된 파드 템플릿을 사용한다.
- 버전 v1 파드 세트를 관리하는 레플리케이션컨트롤러가 있는 경우 이미지의 버전 v2를 사용하도록 파드 템플릿을 수 정하고, 이전 파드 인스턴스를 삭제하면 새 파드로 교체가 가능하다.
- 단점으로는 이전 파드가 삭제되고, 새 파드가 시작되는 동안 짧은 시간의 다운타임이 생긴다.

![image](https://user-images.githubusercontent.com/53685313/211147864-7534a4f2-b16e-4d8b-b3b3-c964a1d7d231.png)


### 새 파드 기동과 이전 파드 사제



- **블루 그린 배포** : 파드의 앞쪽에는 일반적으로 서비스가 배치되어있는데, 새 버전을 실행하는 파드를 불러오는 동안 서비스는 이전 버전에 연결시키고, 새 파드가 모두 실행되면 서비스의 레이블 셀렉터를 변경하여, 서비스를 새 파드로 전환하는 방법 

![image](https://user-images.githubusercontent.com/53685313/211147981-fbe30d30-3114-400c-a681-3e6f729624cd.png)


- 롤링 업데이트 수행
  - 새 파드가 모두 실행된 후 이전 파드를 한 번에 삭제하는 방법 대신 파드를 단계별로 교체하는 방법
  - 이전 레플리케이션컨트롤러를 천천히 스케일 다운하고, 새 파드를 스케일 업해서 수행 가능
  - 서비스의 파드 셀렉터에 이전 파드와 새 파드를 모두 포함하게 해 요청을 두 파드 세트로 보내는 방법
  - 쉽게 설명하자면.. 구 버전의 파드가 삭제되면 신 버전의 파드가 하나 올라오고, 하나씩 교체되는 방법임
![image](https://user-images.githubusercontent.com/53685313/211148206-b5562942-fb12-46f1-a8e8-7a97b35e59a8.png)


### 레플리케이션컨트롤러로 자동 롤링 업데이트 수행

- 한 번에 서비스와 레플리케이션 컨트롤러 생성 yml

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
  - port: 80
    targetPort: 8080
```

- 동일한 이미지 태그로 업데이트 푸시하기
  - 이건 좋은 방법은 사실 아니다.
  - 최신 태그를 수정하는 경우 문제가 되지 않지만 다른 태그(latest가 아닌 v1 태그)로 이미지에 태그를 다는 경우, 워커 노드에서 일단 이미지를 한 번 가져오면 이미지는 노드에 저장되고 동일한 이미지를 사용해 새 파드를 실행할 때 이미지를 다시 가져오지 않는다.
  - 변경한 내용을 같은 이미지 태그로 푸시하면 이미지가 변경되지 않는다.
  - kubelet은 새 파드가 동일한 노드로 스케줄된 경우 이전 버전의 이미지를 실행하고, 이전 버전을 실행하지 않은 노드는 새 이미지를 가져와서 실행하므로 두 가지 버전의 파드가 실행될 수 있는데, 이런 일이 발생하지 않도록 컨테이너의 imagePullPolicy 속성을 Always로 설정해야 한다. 


- 롤링 업데이트 수행 명령어 : `kubectl rolling-update kubia-v1 kubia-v2 --image=luksa/kubia:v2` -> **현재 해당 명령어는 없어짐**

- kubectl rolling-update 를 더 이상 사용하지 않는 이유
  - 앞에서 이야기 했든 kubectl 은 현재 rolling-update 를 deprecated 된 정도가 아니라 아예 없어졌다.
  - kubectl 은 client 인데 client 가 API 를 호출하여 scale up, scale down 을 수행한다
  - client 가 이러한 작업을 요청하다 network 가 끊어지면 어떻게 될까? rolling-update 중간 상태에 머물며 배포 작업이 종료된다
  - 이 책은 시스템의 상태를 선언하고 k8s 가 그것을 달성할 수 있는 가장 좋은 방법을 찾아냄으로써 스스로 그 상태를 달성하도록 하는지에 대해 강조했다. 필요한 명령어를 입력하여 맞추기보다 k8s 가 알아서 그것을 해야한다

### 애플리케이션을 선언적으로 업데이트하기 위한 디플로이먼트 사용하기

- 디플로이먼트는 낮은 수준의 개념으로 간주되는 RC나 레플리카셋을 통해 수행하는 대신 애플리케이션을 배포하고 선언적으로 업데이트하기 위한 높은 수준의 리소스
- 디플로이먼트를 생성하면 레플리카셋 리소스가 그 아래에 생성된다.
- 디플로이먼트를 사용하는 경우 실제 파드는 디플로이먼트가 아닌 디플로이먼트의 레플리카셋에 의해 생성되고 관리된다.
![image](https://user-images.githubusercontent.com/53685313/211149754-b3c0130f-beee-4f63-8288-d4473e7c2b91.png)
- 애플리케이션을 업데이트할 때는 추가 레플리케이션컨트롤러를 도입하고, 두 컨트롤러가 잘 조화되도록 조정해야 하는데, 전체적으로 통제하는 것이 필요하고, 이걸 디플로이먼트가 한다.(디플로이먼트 리소스가 직접 수행하는 것은 아니고 쿠버네티스 컨트롤 플레인에서 실행 중인 컨트롤러 프로세스가 수행)

### 디플로이먼트 생성
- 디플로이먼트는 레이블 셀렉터, 원하는 레플리카 수, 파드 템플릿, 디플로이먼트 리소스가 수정될 때 업데이트 수행 방법을 정의하는 디플로이먼트 전략을 지정하는 필드으로 구성

- 생성 yaml은 교재대로 하면 안됨 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
```

- 디플로이먼트 생성 : `kubectl apply -f kubia-deployment-v1.yml` 교재의 --record도 deprecate되었다.
- 디플로이먼트가 레플리카셋을 생성하고, 디플로이먼트와 파드 템플릿의 해시값이 파드의 중간에 들어가는 것을 확인할 수 있다.
![image](https://user-images.githubusercontent.com/53685313/211150141-f93540af-aba3-449c-ae19-85c2ce9cd08e.png)
- 디플로이먼트는 파드 템플릿의 각 버전마다 하나씩 여러 개의 레플리카셋을 만든다.
- 이와 같이 파드 템플릿의 해시값을 사용하면 디플로이먼트에서 지정된 버전의 파드 템플릿에 관해 항상 동일한 레플리카셋 사용 가능

### 디플로이먼트 업데이트

- 기존에는 RC를 대체하는 새 RC의 이름을 지정하고, 쿠버네티스는 모든 원본 파드를 새 파드로 교체하고, 프로세스가 끝날 때 원본 RC를 삭제했다.
- 이 프로세스 동안 터미널을 열어두고 kubectl이 롤링 업데이트를 완료할때까지 기다려야했다.
- 디플로이먼트를 사용하면 리소스에 정의된 파드 템플릿을 수정하기만 하면 쿠버네티스가 실제 시스템 상태를 리소스에 정의된 상태로 만드는데 필요한 모든 단계를 수행한다.
- 디플로이먼트 전략의 디폴트는 `RollingUpdate`이다.
- `Recreate` 전략 
  - 파드 템플릿을 수정한 후 모든 파드를 삭제하고, 새로운 파드를 만드는 전략
  - 애플리케이션이 여러 버전을 병렬로 실행하는 것을 지원하지 않고, 새 버전을 시작하기 전에 이전 버전을 완전히 중지해야 하는 경우 사용
  - 짧은 서비스 다운타임 발생
- `RollingUpdate` 전략 
  - 이전 파드를 하나씩 제거하고 동시에 새 파드를 추가해 전체 프로세스에서 애플리케이션을 계속 사용 가능
  - 의도하는 레플리카 수보다 많거나 적은 파드 수에 관한 상한과 하한 설정 가능
  - 애플리케이션에서 이전 버전과 새 버전을 동시에 실행할 수 있는 경우에만 이 전략 사용 가능

- 데모 목적으로 롤링 업데이트 속도 느리게 하기 : `kubectl patch deployment kubia -p '{"spec": {"minReadySeconds": 10}}'`
- patch 명령어를 사용해 디플로이먼트 스펙 변경 가능
- 디플로이먼트에서 사용할 이미지 변경하기 : `kubectl set image deployment kubia nodejs=luksa/kubia:v2`
- 로드밸런싱이 v1, v2로 같이 되는지 확인

![image](https://user-images.githubusercontent.com/53685313/211150446-c9e0c6fe-d0cb-4bed-87c0-ccb545574f59.png)

- 이미지 변경 후 디플로이먼트의 파드 템플릿 업데이트
![image](https://user-images.githubusercontent.com/53685313/211150475-ad49c823-8271-4523-907f-a0900ce730e2.png)


- 쿠버네티스 내 리소스 수정하는 방법
  - kubectl edit : 기본 편집기로 오브젝트의 매니페스트를 오픈. 변경 후 파일을 저장하고 편집기를 종료하면 오브젝트가 업데이트
  - kubectl patch : 오브젝트의 개별 속성을 수정
  - kubectl apply : 전체 yml/json 파일의 속성 값을 적용해 오브젝트를 수정. yml/json에 지정된 오브젝트가 아직 없으면 생성된다. 파일에는 리소스의 전체 정의가 포함돼야 한다.
  - kubectl replace : yml/json 파일로 오브젝트를 새 것으로 교체. apply 명령어와 달리 이 명령은 오브젝트가 있어야 함.
  - kubectl set image : 파드, RC의 템플릿, 디플로이먼트, 데몬셋, 잡, 레플리카셋에 정의된 컨테이너 이미지를 변경

- 디플로이먼트의 파드 템플릿이 컨피그맵을 참조하는 경우 컨피그맵을 수정해도, 업데이트를 시작하지 않는다. 애플리케이션의 설정을 수정해야 할 때 업데이트를 시작하는 한 가지 방법은 새 컨피그맵을 만들고 파드 템플릿이 새 컨피그맵을 참조하도록 수정하는 것이다. 
- 업데이트 수행 이후 레플리카셋이 2개 공존하는 것을 확인할 수 있다.
![image](https://user-images.githubusercontent.com/53685313/211150618-e70ede95-82c4-4ba9-b282-10820ad8cb46.png)


### 디플로이먼트 롤백

- 버전 3 배포 : `kubectl set image deployment kubia nodejs=luksa/kubia:v3`
- `kubectl rollout status deployment kubia` 명령어로 롤아웃 진행 상황 확인
![image](https://user-images.githubusercontent.com/53685313/211150761-32bed16a-903c-4a15-baab-d654c926a43c.png)

- 로드 밸런싱 결과
![image](https://user-images.githubusercontent.com/53685313/211150749-972b83a3-a7da-4ddf-8539-e988808e44ec.png)

- 롤백 : `kubectl rollout undo deployment kubia`
- 롤백 후 레플리카셋과 파드 상태
![image](https://user-images.githubusercontent.com/53685313/211150838-d9b6e8e9-7393-411d-b1cc-048ec969ab94.png)

- 롤백 완료 후 상태
![image](https://user-images.githubusercontent.com/53685313/211150861-9c6a96f1-ba99-4a6c-822d-fa2faeb8b8a0.png)

- 롤아웃 프로세스가 진행 중인 동안에도 롤아웃을 중단하려면 실행 취소 명령을 사용할 수 있다. 롤아웃 프로세스 중에 이미 생성된 파드는 제거되고, 이전 파드로 다시 교체된다.
- 특정 디플로이먼트 개정으로 롤백 : `kubectl rollout undo deployment kubia --to-revision=1`
- 디플로이먼트를 수정했을때 비활성화된 레플리카셋이 남아 있는데, 그 남아있는 레플리카셋을 활용해서 특정 버전으로 롤백이 가능한 것이기에, 레플리카셋을 수동으로 삭제하면 안된다.
- 개정 내역의 디폴트 수는 현재 10이다. (10개의 레플리카셋만 남기고, 그 이상이면 삭제하는듯)
![image](https://user-images.githubusercontent.com/53685313/211150970-ff624c86-f699-4091-9d9c-07bd90be977f.png)


### 롤아웃 속도 제어

- 롤링 업데이트 전략의 maxSurge와 maxUnavailable 소성
  - 이 속성 두 개는 디플로이먼트의 롤링 업데이트 중에 한 번에 몇개의 파드를 교체할지를 결정한다.
  - maxSurge와 maxUnavailable이며 디플로이먼트 strategy 속성의 rollingUpdate 속성 아래의 일부로 설정 가능
  - maxSurge 
    - 디플로이먼트가 의도하는 레플리카 수보다 얼마나 많은 파드 인스턴스 수를 허용할 수 있는지 결정
    - 기본적으로 25%로 설정되고, 의도한 개수보다 25% 더 많은 파드 인스턴스 존재 가능
  - maxUnavailable
    - 업데이트 중에 의도하는 레플리카 수를 기준으로 사용할 수 없는 파드 인스턴스 수를 결정
    - 기본적으로 25%로 설정되고, 사용 가능한 파드 인스턴스 수는 의도하는 레플리카 수의 75% 이하로 떨어지면 안된다.
- maxSurge 이해 그림
  - 의도하는 레플리카 수가 3이고, 이러한 속성이 모두 기본적으로 25%이기 때문에 maxSurge는 모든 파드 수가 네 개에 도달하도록 허용
  - maxUnavailable은 사용할 수 없는 파드 허용하지 않는다.(항상 파드 세 개를 사용할 수 있어야 한다.)
![image](https://user-images.githubusercontent.com/53685313/211151155-e5967376-ccd5-426d-8e80-c0b3a8a7e71c.png)
- maxUnavailable 속성 이해 그림
  - 레플리카 한 개를 사용할 수 없으므로 의도하는 레플리카 수가 세 개이면 두개는 사용 가능해야한다.
  - 롤아웃 프로세스에서 즉시 파드 한 개를 삭제하고, 파드 두 개를 만든다.
  - 이러면 파드 두 개를 사용할 수 있고 최대 파드 수를 초과하지 않는다.
  - 파드 두 개를 사용할 수 있게 되면, 기존 나머지 파드 두개 삭제
![image](https://user-images.githubusercontent.com/53685313/211151196-0ba770dc-f11d-43d2-9651-bd89170bfc47.png)


- 쉽게 말해 maxUnavailable 속성은 사용할 수 없는(이전 버전) 파드의 최대 갯수

- v4로 업데이트 : `kubectl set image deployment kubia nodejs=luksa/kubia:v4`
- 업데이트 이후 바로 배포 중단 : `kubectl rollout pause deployment kubia`
- 1개 파드만 생김
![image](https://user-images.githubusercontent.com/53685313/211151378-67fd1c8f-1c8a-45e5-bbdd-36b53db3fd21.png)
- 이렇게 카나리 릴리스를 효과적으로 실행 가능
- 카나리 릴리스는 잘못된 버전의 애플리케이션이 배포돼 모든 사용자에게 영향을 주는 위험을 최소화하는 기술
- 새 버전을 모든 사람에게 롤아웃하는 대신 하나 또는 적은 수의 이전 파드만 새 버전으로 바꾼다.
- 롤아웃 재개 : `kubectl rollout resume deployment kubia`
- `minReadySeconds`에 대한 이해
  - 주요 기능 : 오작동 버전의 배포를 방지하기 위함
  - 해당 속성은 파드를 사용 가능한 것으로 취급하기 전에 새로 만든 파드를 준비할 시간을 지정
  - 파드가 사용 가능할 때까지 롤아웃 프로세스가 계속되지 않는다.
  - 모든 파드의 레디니스 프로브가 성공하면 파드가 준비됨
  - 일반적으로 파드는 실제 트래픽을 수신하기 시작한 후 파드가 준비 상태를 계속 보고할 수 있도록 minReadySeconds를 훨씬 높게 설정한다.

### 잘못된 버전의 롤아웃 방지


- 레디니스 프로브가 추가된 디플로이먼트

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v3
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
```


- 5번 실패하면 HTTP 응답이 계속 실패해서 파드가 서비스의 엔드포인트에서 제거된다.
- 그래서 그 뒤로는 계속 v1으로만 트래픽이 간다.
- 롤아웃 상태를 봐도, 파드가 엔드포인트에서 제거되어서 1개의 파드만 배포하고, 두번째부터는 배포를 안한다. 이게 minReadySeconds를 설정한 결과다. 사용 간으한 것으로 간주되려면 1초 이상 파드가 준비돼 있어야 하고, 사용 가능할 때까지 롤아웃 프로세스는 새 파드를 만들지 않고, maxUnavailable 속성을 0으로 설정했기 때문에 원래 파드도 제거하지 않는 거다.
![image](https://user-images.githubusercontent.com/53685313/211151760-715e630b-c050-4cd8-b689-28084f5e5f52.png)
![image](https://user-images.githubusercontent.com/53685313/211151793-02553973-7e62-4751-8b01-d613abff30b7.png)

- minReadySeconds를 올바르게 설정 안하면, 레디니스 프로브만 정의하는 경우 레디니스 프로브의 첫번째 호출이 성공하면 즉시 새 파드가 사용 가능한 것으로 간주하기 때문에, 잘못된 버전이 배포될 수 있다. minReadySeconds를 꼭 설정하자.
