### ISSUE TITLE
Chapter 5. 서비스 : 클라이언트가 파드를 검색하고 통신을 가능하게 함

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kubernetes-study#6]

**Comment by kmg28801** [comment]
# 서비스
- 파드는 일시적이다. 파드가 다른 파드를 위한 공간을 확보하려고 노드에서 제거되거나, 누군가 파드 수를 줄이거나, 클러스터 노드의 장애로 언제든 다른 노드로 이동할 수 있다.
- 쿠버네티스는 노드에 파드를 스케줄링한 후 파드가 시작되기 바로 전에 파드의 IP 주소를 할당한다. 클라이언트는 서버인 파드의 IP 주소를 미리 알 수 없다.
- 수평 스케일링은 여러 파드가 동일한 서비스를 제공할 수 있음을 의미, 각 파드는 고유한 IP 주소가 있다. 모든 파드는 단일 IP 주소로 액세스할 수 있어야 한다.
- 쿠버네티스의 서비스는 동일한 서비스를 제공하는 파드 그룹에 지속적인 단일 접점을 만들려고 할 때 생성하는 리소스
- 각 서비스는 서비스가 존재하는 동안 절대 바뀌지 않는 IP 주소와 포트가 있다.
- 클라이언트는 해당 IP와 포트로 접속한 다음 해당 서비스를 지원하는 파드 중 하나로 연결
- 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/53685313/206662017-42ad68b9-a4ad-460e-a010-80592517aa19.png">

- 서비스 연결은 서비스 뒷단의 모든 파드로 로드밸런싱된다.
### 기본 서비스 생성 yaml
``` 
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  ports:
  - port: 80 #서비스가 사용할 포트
    targetPort: 8080 #서비스가 포워드할 컨테이너 포트
  selector: # app=kubia 레이블이 있는 모든 파드가 이 서비스에 포함
    app: kubia
```
- 서비스 조회 :  `kubectl get svc`
- 서비스의 기본 목적은 파드 그룹을 클러스터의 다른 파드에 노출시키는 것이지만, 대개 서비스를 외부로 노출하기를 원한다.
- 실행 중인 컨테이너에 원격으로 명령어 실행 `kubectl exec kubia-7nog1 -- curl -s http://10.111.249.153`
  - 명령어의 더블 대시는 kubectl 명령줄 옵션의 끝을 의미. 더블 대시 뒤의 모든 것은 파드 내에서 실행돼야 하는 명령
 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/53685313/206662696-f8ec7356-9f46-4a67-b30f-655342d390d1.png">

- curl은 HTTP 요청을 서비스 IP로 보냄
- 쿠버네티스 서비스 프록시가 연결을 가로채서 세 개의 파드 중 임의의 파드로 요청을 전달
- 해당 파드 내에서 실행 중인 app은 요청을 처리하고 해당 파드의 이름을 포함하는 HTTP 응답을 반환
- curl은 표준 출력으로 응답을 출력하고
- kubectl이 있는 로컬 시스템의 표준 출력에 다시 표시

- 특정 클라이언트의 모든 요청을 매번 같은 파드로 리디렉션하려면 서비스의 세션어피니티 속성을 기본값 None 대신 ClientIP로 설정 필요
- 서비스 프록시는 동일한 클라이언트 IP의 모든 요청을 동일한 파드로 전달
- 쿠버네티스는 None과 ClientIP라는 두 가지 유형의 서비스 세션 어피니티만 지원

### 세션 어피니티 서비스 생성 yaml
``` 
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubia
```

- 서비스는 여러 포트를 지원하기도 함
- 하나의 서비스를 사용해 멀티 포트 서비스를 사용하면 단일 클러스터 IP로 모든 서비스 포트가 노출됨
- 여러 포트가 있는 서비스를 만들 때는 각 포트의 이름을 지정해야 한다.

### 멀티 포트 서비스 생성 yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: kubia
```

## 서비스 검색

- 서비스를 만들면 파드에 액세스할 수 있는 안정적인 IP 주소와 포트가 생긴다. 이건 서비스가 유지되는 동안 변경되지 않는다.

### 환경변수를 통한 서비스 검색
- 파드가 시작되면 쿠버네티스는 해당 시점에 존재하는 각 서비스를 가리키는 환경변수 세트를 초기화
- 클라이언트 파드를 생성하기 전에 서비스를 생성하면 해당 파드의 프로세스는 환경변수를 검사해 서비스의 IP 주소와 포트를 얻을 수 있다.
- 환경 변수 조회 명령어  `kubectl exec kubia-3inly env`
- 현재 클러스터에 kubernetes와 kubia라는 두 개의 서비스가 정의되어, 두 세트의 서비스 관련 환경변수가 목록에 노출됨
- kube-dns : 이 파드는 DNS 서버를 실행하며 클러스터에서 실행 중인 다른 모든 파드는 자동으로 이를 사용하도록 구성
- 파드에서 실행 중인 프로세스에서 수행된 모든 DNS 쿼리는 시스템에서 실행 중인 모든 서비스를 알고 있는 쿠버네티스의 자체 DNS 서버로 처리
- 파드가 내부 DNS 서버를 사용할지 여부는 각 파드 스펙의 dnsPolicy 속성으로 구성할 수 있다.
- 각 서비스는 내부 DNS 서버에서 DNS 항목을 가져오고 서비스 이름을 알고 있는 클라이언트 파드는 환경변수 대신 FQDN으로 액세스 가능
- backend-database.default.svc.cluster.local
 - backend-database는 서비스 이름
 - default는 서비스가 정의된 네임스페이스
 - svc.cluster.local은 모든 클러스터의 로컬 서비스 이름에 사용되는 클러스터의 도메인 접미사
 - 동일한 네임스페이스에 있는 경우 svc.cluster.local 접미사와 네임스페이스는 생략할 수 있다.
 - curl http://kubia.default.svc.cluster.local
 - curl http://kubia.default
 - curl http://kubia
- 파드 컨테이너 내부의 DNS resolver가 구성돼 있기 때문에 네임스페이스와 svc.cluster.local 접미사를 생략할 수 있다.

### 서비스 IP에 핑을 할 수 없는 이유
- 서비스로 curl은 동작하지만 핑은 응답이 없는 이유는, 서비스의 클러스터 IP가 가상 IP이므로 서비스 포트와 결합된 경우에만 의미 있다.

### 서비스 엔드포인트
- 서비스는 파드에 직접 연결되지 않고, 엔드포인트 리소스가 그 사이에 있다.

``` 
kmg48801@cloudshell:~ (kubers-368504)$ kubectl describe svc kubia-loadbalancer
Name:                     kubia-loadbalancer
Namespace:                default
Labels:                   <none>
Annotations:              cloud.google.com/neg: {"ingress":true}
Selector:                 app=kubia
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.1.1.160
IPs:                      10.1.1.160
LoadBalancer Ingress:     34.64.123.50
Port:                     <unset>  80/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  31697/TCP
Endpoints:                10.0.128.28:8080,10.0.128.29:8080,10.0.128.30:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  2m43s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   107s   service-controller  Ensured load balancer
``` 
- 엔드포인트 리소스는 서비스로 노출되는 파드의 IP 주소와 포트 목록
- 엔드포인트 리소스는 다른 쿠버네티스 리소스와 유사하므로 kubectl get으로 정보를 가져올 수 있다.
- 파드 셀렉터는 IP와 포트 목록을 작성하는 데 사용되며 엔드포인트 리소스에 저장된다.
- 클라이언트가 서비스에 연결하면 서비스 프록시는 이들 중 하나의 IP와 포트 쌍을 선택하고 들어온 연결을 대상 파드의 수신 대기 서버로 전달

### 서비스 엔드포인트 수동 구성

- 서비스의 엔드포인트를 서비스와 분리하면 엔드포인트를 수동으로 구성하고 업데이트 가능
- 파드 셀렉터 없이 서비스를 만들면 쿠버네티스는 엔드포인트 리소스를 만들지 못한다.

### 엔드포인트 생성 yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service # 엔드포인트 오브젝트의 이름은 서비스 이름과 일치해야함
subsets:
  - addresses:
    - ip: 11.11.11.11 # 서비스가 연결 전달한 엔드포인트 IP
    - ip: 22.22.22.22
    ports:
    - port: 80 # 엔드포인트 대상 포트
```

- 엔드포인트는 별도의 리소스이고, 서비스 속성이 아니다.
- 셀렉터가 없는 서비스의 서비스 이름은 엔드포인트 오브젝트 이름과 동일해야 한다.

### 외부 서비스를 위한 별칭
- 외부 서비스의 별칭으로 사용되는 서비스를 만들려면 유형 필드를 ExternalName으로 설정해야 한다.
- 서비스가 생성되면 파드는 서비스의 FQDN을 사용하는 대신 external-service.default.svc.cluster.local 도메인 이름으로 외부 서비스에 연결할 수 있다.
- ExternalName 서비스는 DNS 레벨에서만 구현된다.

### 외부 서비스 yaml
```
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: ExternalName # 서비스 유형을 ExternalName으로 설정
  externalName: someapi.somecompany.com #실제 서비스의 정규화된 도메인 이름 (FQDN)
  ports:
  - port: 80
```

### 외부 클라이언트에 서비스 노출
- 노드포트로 서비스 유형 설정 : 노드포트 서비스의 경우 각 클러스터 노드는 노드 자체에서 포트를 열고 해당 포트로 수신된 트래픽을 서비스로 전달
- 서비스는 내부 클러스터 IP와 포트로 액세스할 수 있을 뿐만 아니라 모든 노드의 전용 포트로도 액세스 가능
- 서비스 유형을 로드밸런서로 설정 : 쿠버네티스가 실행 중인 클라우드 인프라에서 프로비저닝된 전용 로드밸런서로 서비스에 액세스할 수 있다. 로드밸런서는 트래픽을 모든 노드의 노드포트로 전달한다.
- 인그레스 리소스 생성 : HTTP 레벨에서 작동하고 하나의 IP + Path Routing 방식

### 노드포트 서비스
- 파드 세트를 외부 클라이언트에 노출시키는 첫 번째 방법은 서비스를 생성하고, 유형을 노드포트로 설정하는 것
- 노드포트 서비스를 만들면 쿠버네티스는 모든 노드에 특정 포트를 할당하고 서비스를 구성하는 파드로 들어오는 연결을 전달한다.

### 노드포트 서비스 yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort # 서비스 유형을 노드포트로 설정
  ports:
  - port: 80 # 서비스 내부 클러스터 IP 포트
    targetPort: 8080 #서비스 대상 파드의 포트
    nodePort: 30123 #각 클러스터 노드의 포트 30123으로 서비스에 액세스 가능
  selector:
    app: kubia
```

- nodePort를 생략하면 쿠버네티스가 임의의 포트를 선택한다.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/53685313/206666636-2a563a5c-c775-4c63-bda3-aa8df11a7b2b.png">
- 노드포트로 서비스에 액세스하려면 해당 노드포트에 대한 외부 연결을 허용하도록 방화벽을 구성해야 한다.

### 외부 로드밸런서로 서비스 노출
- 로드밸런서는 공개적으로 액세스 가능한 고유한 IP 주소를 가지며 모든 연결을 서비스로 전달
- 로드밸런서 서비스는 노드포트 서비스의 확장이다.

### 로드밸런서 서비스 yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kubia-loadbalancer
spec:
  type: LoadBalancer # 이 유형의 서비스는 쿠버네티스 클러스터를 호스팅하는 인프라에서 로드밸런서를 얻는다.
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubia
```
- 서비스를 생성한 후 클라우드 인프라가 로드밸런서를 생성하고 IP 주소를 서비스 오브젝트에 쓰는 데 시간이 걸리기에, External IP는 즉각적으로 생기지 않는다.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/53685313/206667093-821492f6-d4c6-43bd-9783-ab8b75008323.png">

### 외부 연결의 특성 이해
- 외부의 연결을 수신한 노드에서 실행 중인 파드로만 외부 트래픽을 전달하도록 서비스를 구성해 네트워크 홉을 줄일 수 있다. (선택된 노드에 존재하는 파드로만 연결)
- 서비스의 스펙 섹셕의 externalTrafficPolicy 필드를 Local로 설정하면 된다.
- 서비스 정의에 이 설정이 포함돼 있고 서비스의 노드포트로 외부 연결이 열린 경우 서비스 프록시는 로컬에 실행 중인 파드를 선택한다.
- 로컬 파드가 존재하지 않으면 연결이 중단된다.
- 클러스터 내의 클라이언트가 서비스로 연결할 때 서비스의 파드는 클라이언트의 IP 주소를 얻을 수 있는데, 노드포트로 연결을 수신하면 패킷에서 소스 네트워크 주소 변환이 수행되므로 패킷의 소스 IP가 변경된다.

### 인그레스
- 인그레스는 한 IP 주소로 수십 개의 서비스에 접근이 가능하도록 지원해준다.
- 클라이언트가 HTTP 요청을 인그레스에 보낼 때, 요청한 호스트와 경로에 따라 요청을 전달할 서비스가 결정된다.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/53685313/206667689-686f6965-c41b-4d98-9ab9-c440fdbc84c7.png">
- 인그레스는 네트워크 스택의 7계층이므로 서비스가 할 수 없는 쿠키 기반 세션 어피니티 등과 같은 기능을 제공한다.
- 인그레스 리소스를 작동시키려면 클러스터에 인그레스 컨트롤러를 실행해야 한다.
- minikube에서는 애드온 활성화 -> `minikube addons enable ingress`

### 인그레스 생성 yaml (교재대로 하면 안됨)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  defaultBackend:
    service:
      name: kubia-nodeport
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubia-nodeport
            port:
              number: 80

```

- 인그레스 생성 시 주의할 점으로는 default Backend 설정을 안하면 404 ERROR를 받는다는 것 (기본 백엔드를 지정하지 않으면 GKE은 404를 반환하는 기본 백엔드를 제공합니다. 이것은 kube-system 네임스페이스의 클러스터에 default-http-backend NodePort 서비스로 생성됩니다.)
- 참고 URL : https://cloud.google.com/kubernetes-engine/docs/concepts/ingress?hl=ko

### 인그레스에서 사용할 서비스 yaml

```
apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort # 서비스 유형을 노드포트로 설정
  ports:
  - port: 80 # 서비스 내부 클러스터 IP 포트
    targetPort: 8080 #서비스 대상 파드의 포트
  selector:
    app: kubia
```

<img width="628" alt="image" src="https://user-images.githubusercontent.com/53685313/206667951-0fed57b0-3012-4c07-9022-a024623e4ee4.png">
- 클라이언트는 kubia.example.com의 DNS 조회 수행
- DNS서버가 인그레스 컨트롤러의 IP를 반환
- 클라이언트는 HTTP 요청을 인그레스 컨트롤러로 전송하고 헤더에 kubia.example.com 지정
- 컨트롤러는 해당 헤더에서 클라이언트가 액세스하려는 서비스를 결정
- 서비스와 관련된 엔드포인트 오브젝트로 파드 IP 조회
- 클라이언트 요청을 파드에 전달
- 하나의 인그레스로 여러 서비스를 노출할 수도 있다.

### TLS 트래픽 처리용 인그레스 구성

- TLS 연결을 하게 되면 클라이언트와 컨트롤러 간의 통신은 암호화되지만, 컨트롤러와 백엔드 파드 간의 통신은 암호화되지 않는다.
- 파드가 웹 서버를 실행하는 경우 HTTP 트래픽만 허용하고, 인그레스 컨트롤러가 TLS와 관련된 모든 것을 처리하도록 구성
- 이렇게 구성하려면 인증서와 개인 키를 인그레스에 첨부 필요하다.
- 이 두개는 시크릿이라는 쿠버네티스 리소스에 저장하며 인그레스 매니페스트에서 참조한다.
- 키 생성 : `openssl genrsa -out tls.key 2048`
- 인증서 생성 : `openssl req -new -x509 -key tls.key tls.key -out tls.cert -days 360 -subj /CN=kubia.example.com`
- 시크릿 생성 : `kubectl create secret tls tls-secret --cert=tls.cert --key=tls.key`
- 인증서를 직접 서명하는 대신 CSR 리소스를 만들어 인증서에 서명하는 것도 가능하다,
- 사용자 또는 해당 애플리케이션이 일반 인증서 요청을 생성할 수 있고, CSR에 넣으면 그다음 운영자나 자동화된 프로세스가 다음 요청을 승인할 수 있다. `kubectl certificate approve <name of the CSR>


### TLS 트래픽 처리용 인그레스
``` 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  tls:
  - hosts:
    - kubia.example.com
    secretName: tls-secret
  defaultBackend:
    service:
      name: kubia-nodeport
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubia-nodeport
            port:
              number: 80
``` 

- curl 옵션으로 https 접근 시 -k 옵션 필요(교재에서는 -v 까지 줬는데 이건 디버깅 용)
``` 
kmg48801@cloudshell:~ (kubers-368504)$ curl -k https://kubia.example.com/a
You've hit kubia-5c7s9
kmg48801@cloudshell:~ (kubers-368504)$ curl -k https://kubia.example.com/a
You've hit kubia-5c7s9
kmg48801@cloudshell:~ (kubers-368504)$ curl -k https://kubia.example.com/a
You've hit kubia-4hrwk
``` 

### 레디니스 프로브
- 파드는 구성에 시간이 걸리거나 데이터를 로드하는 데 시간이 필요할 수도 있고, 첫번째 사용자 요청이 너무 오래 걸리거나 사용자 경험에 영향을 미치는 것을 방지하고자 준비절차를 수행해야 할 필요가 있다.
- 레디니스 프로브는 주기적으로 호출되며 특정 파드가 클라이언트 요청을 수신할 수 있는지를 결정한다.
- 레디니스 프로브 유형
  - Exec 프로브 : 프로세스를 실행하는 컨테이너의 상태를 프로세스의 종료 상태 코드로 결정
  - HTTP GET 프로브 : HTTP GET 요청을 컨테이너로 보내고 응답의 HTTP 상태 코드를 보고 컨테이너 준비 여부 결정
  - TCP 소켓 프로브 : 컨테이너의 지정된 포트로 TCP 연결, 소켓이 연결되면 컨테이너가 준비된 것으로 간주

### 레디니스 프로브 동작
- 쿠버네티스는 첫 번째 레디니스 점검을 수행하기 전 구성 가능한 시간이 경과하기를 기다리도록 구성
- 파드가 준비되지 않았다고 하면 서비스에서 제거, 파드가 다시 준비되면 서비스에 다시 추가 (실제로는 엔드포인트에 추가되거나 제거됨)
- 라이브니스 프로브와 달리 컨테이너가 준비 상태 점검에 실패하더라도 컨테이너가 종료되거나 다시 시작되지 않음
- 라이브니스 프로브는 상태가 좋지 않은 컨테이너를 제거하고 새로운 컨테이너로 교체해 파드의 상태를 정상으로 유지하는 반면, 레디니스 프로브는 요청을 처리할 준비가 된 파드의 컨테이너만 요청 가능하도록 엔드포인트에서 추가, 제거함

![image](https://user-images.githubusercontent.com/53685313/206893972-111a3500-96f2-4766-9a21-6b58fe9d9fe1.png)

### 레디니스 프로브를 가진 레플리카셋 (교재에서는 레플리케이션컨트롤러로 했지만, 레플리케이션컨트롤러는 이제 안쓰이기 때문에 replicaset으로 실습 진행)
``` 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready  
``` 

- 해당 레디니스 프로브는 컨테이너 내부에서 ls /var/ready 명령어를 주기적으로 수행한다. ls 명령어는 파일이 존재하면 종료 코드 0 반환하고 그렇지 않으면 0 아닌 값 반환
- 아래 상태값을 보면 파일이 없기 때문에 READY 열이 0인 것을 확인

``` 
kmg48801@cloudshell:~ (kubers-368504)$ kubectl get po
NAME          READY   STATUS    RESTARTS   AGE
kubia-2l9dg   0/1     Running   0          2m27s
kubia-fh46k   0/1     Running   0          2m27s
kubia-xgx5s   0/1     Running   0          2m27s
kmg48801@cloudshell:~ (kubers-368504)$
``` 

- `kubectl exec kubia-fh46k -- touch /var/ready` 명령어 수행 -> 2번째 파드만 READY 됨

``` 
kmg48801@cloudshell:~ (kubers-368504)$ kubectl get po
NAME          READY   STATUS    RESTARTS   AGE
kubia-2l9dg   0/1     Running   0          3m50s
kubia-fh46k   1/1     Running   0          3m50s
kubia-xgx5s   0/1     Running   0          3m50s
kmg48801@cloudshell:~ (kubers-368504)$
``` 
- 레디니스 프로브는 항상 정의해야 한다.
- 파드에 레디니스 프로브를 추가하지 않으면 파드가 시작하는 즉시 서비스 엔드포인트가 된다.
- 애플리케이션이 로딩되는데 오래 걸리는 경우 클라이언트의 서비스 요청이 로딩되는 시점으로 오면 클라이언트는 connection refuse 에러를 맞게 된다.
- 쿠버네티스는 파드를 삭제하자마자 모든 서비스에서 파드를 제거하기 때문에 종료 절차에서 레디니스 프로브가 실행하도록 설정하면 안된다.

### 서비스 문제 해결
- 먼저 외부가 아닌 클러스터 내에서 서비스의 클러스터 IP에 연결되는지 확인
- 서비스에 액세스할 수 있는지 확인하려고 서비스 IP로 핑을 하지말자(VIP라 안됨)
- 레디니스 프로브를 정의했다면 성공했는지 확인하자.
- 파드가 서비스의 일부인지 확인하려면 kubectl get endpoints를 사용해 해당 엔드포인트 오브젝트를 확인한다.
- FQDN이나 그 일부로 서비스에 액세스할때 작동하지 않는 경우, FQDN 대신 클러스터 IP를 사용해 액세스할 수 있는지 확인
- 대상 포트가 아닌 서비스로 노출된 포트에 연결하고 있는지 확인
- 파드 IP에 직접 연결해 파드가 올바른 포트에 연결돼 있는지 확인
- 파드 IP로 애플리케이션에 액세스할 수 없는 경우 애플리케이션이 로컬호스트에만 바인딩하고 있는지 확인

### 요약
- 안정된 단일 IP 주소와 포트로 특정 레이블 셀렉터와 일치하는 여러 개의 파드를 노출
- 기본적으로 클러스터 내부에서 서비스에 액세스할 수 있지만 유형을 노드포트 or 로드밸런서로 설정해 클러스터 외부에서 서비스에 액세스하는 것도 가능하다.
- 파드가 환경변수를 검색해 IP 주소와 포트로 서비스를 검색할 수 있다.
- 관련된 엔드포인트 리소스를 만드는 대신 셀렉터 설정 없이 서비스 리소스를 생성해 클러스터 외부에 있는 서비스를 검색하고 통신할 수 있다.
- ExternalName 서비스 유형으로 외부 서비스에대한 DNS CNAME을 제공한다.
- 단일 인그레스로 여러 HTTP 서비스를 노출한다.
- 파드 컨테이너의 레디니스 프로브는 파드를 서비스 엔드포인트에 포함해야 하는지 여부를 결정한다.
- 헤드리스 서비스를 생성하면 DNS로 파드 IP를 검색할 수 있다.

### 쿠버 치트 history

``` 
kubectl apply -f kubia-svc.yml
kubectl delete svc --all
kubectl get po
kubectl delete po --all
kubectl apply -f kubia-replicaset.yaml
kubectl get rs
kubectl get po
kubectl exec kubia-dq8nv -- curl http://10.1.3.80


curl http://kubia.default.svc.cluster.local
curl http://kubia.default
curl http://kubia

kubectl describe svc kubia
kubectl get endpoints kubia
kubectl get svc
kubectl delet svc kubia
kubectl delete svc --all
kubectl apply -f external-service.yml
kubectl apply -f external-service-endpoints.yml
kubectl delete po --all
kubectl get po
kubectl exec kubia-gj7db env

kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}'


kmg48801@cloudshell:~ (kubers-368504)$ kubectl describe svc kubia-loadbalancer
Name:                     kubia-loadbalancer
Namespace:                default
Labels:                   <none>
Annotations:              cloud.google.com/neg: {"ingress":true}
Selector:                 app=kubia
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.1.1.160
IPs:                      10.1.1.160
LoadBalancer Ingress:     34.64.123.50
Port:                     <unset>  80/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  31697/TCP
Endpoints:                10.0.128.28:8080,10.0.128.29:8080,10.0.128.30:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  2m43s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   107s   service-controller  Ensured load balancer
```
