### ISSUE TITLE
Chapter 6. 볼륨: 컨테이너에 디스크 스토리지 연결

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kubernetes-study#7]

**Comment by kmg28801** [comment]
https://rust-stilton-929.notion.site/c92ca7422f3a4e1686b3ca3aab9bbace

**Comment by kmg28801** [comment]
p.278
`kubectl exec -it mongodb mongo`는 실행안됨
`kubectl exec -it mongodb mongosh` 로 실행

**Comment by kmg28801** [comment]
pvc 생성 yml

```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc # PVC 이름으로 나중에 파드의 볼륨을 요청할때 사용
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
